### ISSUE TITLE
hwloc/autogen/config.h error

### ISSUE THREAD

**Issue by marieBvr** [son-of-gridengine/sge#10]
Dear developers,
I am trying to install SGE on my linux 18.04.
When I launch `./aimk -no-java -no-jni -no-secure -spool-classic` I encounter the following error:
 ```
cc -DSGE_ARCH_STRING=\"lx-amd64\" -O2 -Wstrict-prototypes -DLINUXAMD64 -DLINUXAMD64 -D_GNU_SOURCE -DGETHOSTBYNAME_R6 -DGETHOSTBYADDR_R8  -DTARGET_64BIT  -DSGE_PQS_API -DSPOOLING_classic  -DHAVE_HWLOC=1 -DNO_JNI -DCOMPILE_DC -D__SGE_COMPILE_WITH_GETTEXT__  -D__SGE_NO_USERMAPPING__ -I../common -I../libs -I../libs/uti -I../libs/juti -I../libs/gdi -I../libs/japi -I../libs/sgeobj -I../libs/cull -I../libs/comm -I../libs/comm/lists -I../libs/sched -I../libs/evc -I../libs/evm -I../libs/mir -I../daemons/common -I../daemons/qmaster -I../daemons/execd -I../clients/common -I. -fPIC -c ../libs/sgeobj/sge_binding.c
In file included from ../libs/uti/sge_binding_hlp.h:45:0,
                 from ../libs/sgeobj/sge_binding.h:43,
                 from ../libs/sgeobj/sge_binding.c:39:
../libs/uti/hwloc.h:49:10: fatal error: hwloc/autogen/config.h: No file or folder of this kind
 #include <hwloc/autogen/config.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
../libs/sgeobj/Makefile:184: recipe for target 'sge_binding.o' failed
make: *** [sge_binding.o] Error 1
not done
```

Could you help me resolve this problem ?

Marie

**Comment by danpovey** [comment]
Sorry, this repo is pretty dormant, it is not the current upstream of SoGE.  In fact, there is no such upstream development, gridengine is pretty much orphaned at the moment.
I would ask at:
users@gridengine.org
or preferably, just find a binary package (I know they exist for Debian/Ubuntu, not sure about RedHat/CentOS).
Personally if I were starting afresh with a cluster, I would probably go with slurm, as it is actively maintained.  Or maybe fork out for Univa GridEngine.

**Comment by marieBvr** [comment]
Thanks for your feedback @danpovey.
I will follow your recommendations.

**Comment by Kunzol** [comment]
In best case, installing the package "libhwloc-dev" solves the problem.

https://packages.ubuntu.com/disco/libhwloc-dev
