### ISSUE TITLE
Importing the original repo

### ISSUE THREAD

**Issue by danpovey** [son-of-gridengine/sge#6]
Making a separate issue for this.

@Kunzoi told me by email:
```
as written on Github, here is the link to the Git repo I created from the DARCS repo of SGE.

https://gitlab.bfabric.org/schmidt/sge

As far as I can see this is equal to the DARCS repo (diff). 
```
I tried importing his repo and it's the same as this repo where expected.
```
 README                                                               |  7 -------
 README.md                                                            | 15 +++++++++++++++
 debian/rules                                                         |  0
 ... all other diffs are empty.
```
Unfortunately that's a problem because I previously determined that this repo is out of sync with the release tarballs that the Debian people were using-- and it has been out of sync for some time into the past, at least since 8.1.3.  Basically, the release tags in this repo don't line up with the release tarballs.  It seems Dave had two repos.  This repo may correspond to his "master" version, but there was another "release" version I believe.. or something like that.  Do you think you could try to do your same process for the release version?  It think it's more efficient than my process.  

Once you have that, I can test whether it lines up with what the Debian people have, and try figure out whether his master repo had important differences from the release repo that we need to keep.

**Comment by Kunzol** [comment]
I don't know which  the "release-tarballs" of the Debian people are and where I can find them.

But the one I have (from darcs) is definitely the latest development branch.
All other versions will not compile under Stretch because of OpenSSL 1.1. 

I just tried it and the darcs clone  builds Debian Stretch packages as version 8.1.9.

    sge_8.1.9-1_amd64.deb  
    sge-common_8.1.9-1_all.deb  
    sge-dbg_8.1.9-1_amd64.deb  
    sge-doc_8.1.9-1_all.deb

But without the latest patches I sent to the darcs ticket system, the master does not work.

**Comment by 0xaf1f** [comment]
> I don't know which the "release-tarballs" of the Debian people are and where I can find them.

Here is 8.1.9+dfsg

http://http.debian.net/debian/pool/main/g/gridengine/gridengine_8.1.9+dfsg.orig.tar.gz

> But the one I have (from darcs) is definitely the latest development branch.
All other versions will not compile under Stretch because of OpenSSL 1.1.

OpenSSL 1.0 is available in stretch. You get it from the `libssl1.0-dev` package: https://packages.debian.org/stretch/libssl1.0-dev

**Comment by danpovey** [comment]
I am mostly referring to the debian repo here
 https://salsa.debian.org/hpc-team/gridengine.git 
and @0xaf1f  told me they base its source on the release tarballs from Dave (which I don't know exactly where they are from).

Anyway the differences between our repos and theirs are pretty small and I'm not sure how much we care that our tags of older versions don't fully line up with theirs-- I think we're mostly concerned about the future, not the past.  If it's OK with @0xaf1f, I'd rather just continue from the current master, and apply Marco's patches, and get something that works without worrying about past release tags are 100% correct.

@Kunzol, how did you determine that your repo is smaller than this one?

**Comment by 0xaf1f** [comment]
> @0xaf1f told me they base its source on the release tarballs from Dave (which I don't know exactly where they are from).

Those used to be at http://arc.liv.ac.uk/downloads/SGE/releases, but it looks like Dave made them available at https://sourceforge.net/projects/gridengine/.

>  If it's OK with @0xaf1f, I'd rather just continue from the current master, and apply Marco's patches, and get something that works without worrying about past release tags are 100% correct.

I wonder if those tags should instead be deleted then. They didn't actually exist in this repository to begin with and, if they don't represent the labeled release, then it's probably better not to name them as such.

**Comment by danpovey** [comment]
Let me try to recover the correct release tags.  I think the correct source
might be
  https://gitlab.com/loveshack/sge-release
I hope I can do it within a day or two.

**Comment by Kunzol** [comment]
From the commit numbers and the date, this one is the "newest", which I call the "developer-branch": 

https://arc.liv.ac.uk/trac/SGE/browser/sge

From this I made the git. 

The release is the version tagged with 819, which is a bit behind. I assume this is the start point for packaging for several distros (debian, redhat, ...). I suggest we should switch to version 9.0.0 as soon as we are done adding all patches and get a first stable release. 8.1.8 is anyway not compatible with 8.1.9.

Debian has both libssl-1.1 and libssl-1.0. As we have the SGE code which works with 1.1 we should go for the newest.

We have now two "branches" we have to bring together. 
* The developer branch plus patches in the ticket system, which are mainly fixes for the functionality
* The debian gitlab branch maintained by @0xaf1f which has a lot of fixes for packaging

Both are important and the only question is: Which one should we start with.

Personally I would start with the "developer branch" and go through each commit of @0xaf1f debian gitlab and add them. 

We should always keep in mind that SGE is not only for Debian even if we do not have all platforms (Solaris, Windows, Redhat, ...) available to test. Currently I think we are still in line with this.

> @Kunzol, how did you determine that your repo is smaller than this one?

@danpovey, I clone it  and use "du"

**Comment by danpovey** [comment]
For the immediate future let's not get Debian packaging issues involved,
let's leave their stuff separate in terms of git repos while we stabilize
things and I learn about how the build works.

The two branches that I think we need to combine somehow into one repo are
Dave's "sge" repo and his "sge-release" repo.  They have about the same set
of tags, for releases, but they are slightly out of sync with each other.
From Mark Dixon, on the list:

  "You might need to be careful when cloning. You may have already
discovered this, but Dave used darcs which doesn't store history linearly.
He exposes two main repos to git users: one which I think was effectively
his master branch and a second containing all the releases."

We probably need his master branch for the latest changes, but I'd rather
not lose the history, and his master branch seems to be out of sync with
his developer branch in terms of the older tags.  I'm trying right now to
at least verify that his "release" branch agrees with what the Debian
people were using for their releases.  So we may want to use his "release"
branch for history (so we have an accurate history) while using the master
version for future development.

**Comment by danpovey** [comment]
I'm having trouble getting rid of commits that fail fsck.
Marco, is there any chance you could do your same process as you did before to get the git version of  the darcs repo, but on the following source instead?
https://arc.liv.ac.uk/repos/darcs/sge-release/

**Comment by danpovey** [comment]
OK, I have recreated the repo based on Marco's darcs-to-git.  The master comes from Dave's 'sge' repo and the tags come from Dave's 'sge-release' repo.  Marco, let's focus on getting your patches merged so we can compile without having to get the old OpenSSL source.

**Comment by Kunzol** [comment]
Interesting, the github clone is still much (5 times!) larger that the one I produced with 'darcs-to-git'.

    $ git clone https://github.com/son-of-gridengine/sge.git
    Cloning into 'sge'...
    remote: Counting objects: 72419, done.
    remote: Compressing objects: 100% (13/13), done.
    remote: Total 72419 (delta 34), reused 24 (delta 24), pack-reused 72382
    Receiving objects: 100% (72419/72419), 407.35 MiB | 25.73 MiB/s, done.
    Resolving deltas: 100% (56529/56529), done.
    $ du -sh sge
    465M    sge
    $ git clone https://gitlab.bfabric.org/schmidt/sge.git mysge
    Cloning into 'mysge'...
    remote: Counting objects: 64836, done.
    remote: Compressing objects: 100% (13681/13681), done.
    remote: Total 64836 (delta 49488), reused 64836 (delta 49488)
    Receiving objects: 100% (64836/64836), 27.75 MiB | 29.59 MiB/s, done.
    Resolving deltas: 100% (49488/49488), done.
    $ du -sh mysge
    85M     mysge

**Comment by danpovey** [comment]
Probably it didn't garbage-collect/clean up old, unreachable objects.  I
think it's hard to do what that requires without deleting the project on
github.

According to this
https://stackoverflow.com/questions/3162786/how-can-i-trigger-garbage-collection-on-a-git-remote-repository

you can't really do it, but automatic garbage collection should reduce the
size of the repo eventually.

**Comment by Kunzol** [comment]
You are right, after I did a "git gc --aggressive" it shrunk to about 85M, which is the same size as my clone. 
Let's see if the automatic garbage collector will shrink it.

Anyway. We finishend importing the original source from the darcs repo at Liverpool. 
I will now add the missing patches and create pull requests. 
Best we close this and make new issues for the pull requests if needed.

Thanks for working together to make this a success!

**Comment by danpovey** [comment]
I'll try git gc --aggressive and then git push with the --mirror option, if github will allow it.

No -- thank you!   
Closing this issue.
